/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aula_7;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrator
 */
public class Escolhendo_Signo extends javax.swing.JFrame {

    /**
     * Creates new form Escolhendo_Signo
     */
    public Escolhendo_Signo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBGrupoOpcoes = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRAries = new javax.swing.JRadioButton();
        jRTouro = new javax.swing.JRadioButton();
        jRGemeos = new javax.swing.JRadioButton();
        jRCancer = new javax.swing.JRadioButton();
        jRLeao = new javax.swing.JRadioButton();
        jRVirgem = new javax.swing.JRadioButton();
        jRLibra = new javax.swing.JRadioButton();
        jREscorpiao = new javax.swing.JRadioButton();
        jRSagitario = new javax.swing.JRadioButton();
        jRCapricornio = new javax.swing.JRadioButton();
        jRPeixes = new javax.swing.JRadioButton();
        jRAquario = new javax.swing.JRadioButton();
        jBSair = new javax.swing.JToggleButton();
        jBSigno = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Signos");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Signos - Escolha o seu:");

        jBGrupoOpcoes.add(jRAries);
        jRAries.setText("Aries");

        jBGrupoOpcoes.add(jRTouro);
        jRTouro.setText("Touro");
        jRTouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRTouroActionPerformed(evt);
            }
        });

        jBGrupoOpcoes.add(jRGemeos);
        jRGemeos.setText("Gêmeos");

        jBGrupoOpcoes.add(jRCancer);
        jRCancer.setText("Câncer");

        jBGrupoOpcoes.add(jRLeao);
        jRLeao.setText("Leão");

        jBGrupoOpcoes.add(jRVirgem);
        jRVirgem.setText("Virgem");

        jBGrupoOpcoes.add(jRLibra);
        jRLibra.setText("Libra");

        jBGrupoOpcoes.add(jREscorpiao);
        jREscorpiao.setText("Escorpião");

        jBGrupoOpcoes.add(jRSagitario);
        jRSagitario.setText("Sagitário");

        jBGrupoOpcoes.add(jRCapricornio);
        jRCapricornio.setText("Capricórnio");

        jBGrupoOpcoes.add(jRPeixes);
        jRPeixes.setText("Peixes");

        jBGrupoOpcoes.add(jRAquario);
        jRAquario.setText("Aquário");

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jBSigno.setText("Veja o que diz seu signo:");
        jBSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSignoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRAries)
                                    .addComponent(jRTouro)
                                    .addComponent(jRGemeos)
                                    .addComponent(jRCancer))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRLeao)
                                    .addComponent(jRVirgem)
                                    .addComponent(jREscorpiao)
                                    .addComponent(jRLibra)))
                            .addComponent(jBSigno))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRCapricornio)
                            .addComponent(jRSagitario)
                            .addComponent(jRPeixes)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jBSair, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRAquario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRAries)
                    .addComponent(jRLeao)
                    .addComponent(jRSagitario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRTouro)
                    .addComponent(jRVirgem)
                    .addComponent(jRCapricornio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRGemeos)
                    .addComponent(jRLibra)
                    .addComponent(jRAquario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRCancer)
                    .addComponent(jREscorpiao)
                    .addComponent(jRPeixes))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSair)
                    .addComponent(jBSigno))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRTouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRTouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRTouroActionPerformed

    private void jBSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSignoActionPerformed
        // TODO add your handling code here:
String selectedSign = null;
if (jRAries.isSelected()) {
        selectedSign = jRAries.getText();
} else if (jRTouro.isSelected()) {
        selectedSign = jRTouro.getText();
} else if (jRGemeos.isSelected()) {
        selectedSign = jRGemeos.getText();
} else if (jRCancer.isSelected()) {
        selectedSign = jRCancer.getText();
} else if (jRLeao.isSelected()) {
        selectedSign = jRLeao.getText();
} else if (jRVirgem.isSelected()) {
        selectedSign = jRVirgem.getText();
} else if (jRLibra.isSelected()) {
        selectedSign = jRLibra.getText();
} else if (jREscorpiao.isSelected()) {
        selectedSign = jREscorpiao.getText();
} else if (jRSagitario.isSelected()) {
        selectedSign = jRSagitario.getText();
} else if (jRCapricornio.isSelected()) {
        selectedSign = jRCapricornio.getText();
} else if (jRPeixes.isSelected()) {
        selectedSign = jRPeixes.getText();
} else if (jRAquario.isSelected()) {
        selectedSign = jRAquario.getText();
}

String mensagem;
switch(selectedSign){
    case "Aries":
        mensagem = "Eu sou o líder e vou atrás do que quero com coragem.";
        break;
    case "Touro":
        mensagem = "A segurança e a estabilidade são minhas prioridades.";
        break;
    case "Gêmeos":
        mensagem = "Eu adoro explorar ideias e trocar informações.";
        break;
    case "Câncer":
        mensagem = "A proteção e o cuidado com aqueles que amo são essenciais.";
        break;
    case "Leão":
        mensagem = "Eu brilho com confiança e busco ser reconhecido.";
        break;
    case "Virgem":
        mensagem = "A organização e a atenção aos detalhes são minha especialidade.";
        break;
    case "Libra":
        mensagem = "Eu busco equilíbrio e harmonia em todas as minhas relações.";
        break;
    case "Escorpião":
        mensagem = "A intensidade e a profundidade são o que me movem.";
        break;
    case "Sagitário":
        mensagem = "Eu sou aventureiro e sempre em busca de novos horizontes.";
        break;
    case "Capricórnio":
        mensagem = "O sucesso e a responsabilidade são minhas maiores motivações.";
        break;
    case "Peixes":
        mensagem = "A empatia e a intuição guiam meu caminho.";
        break;
    case "Aquário":
        mensagem = "Eu valorizo a originalidade e a inovação.";
        break;
    default:
        mensagem = "Nenhum signo selecionado.";
        break;
}
    JOptionPane.showMessageDialog(this, mensagem);
    }//GEN-LAST:event_jBSignoActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_jBSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escolhendo_Signo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escolhendo_Signo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escolhendo_Signo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escolhendo_Signo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escolhendo_Signo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jBGrupoOpcoes;
    private javax.swing.JToggleButton jBSair;
    private javax.swing.JToggleButton jBSigno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRAquario;
    private javax.swing.JRadioButton jRAries;
    private javax.swing.JRadioButton jRCancer;
    private javax.swing.JRadioButton jRCapricornio;
    private javax.swing.JRadioButton jREscorpiao;
    private javax.swing.JRadioButton jRGemeos;
    private javax.swing.JRadioButton jRLeao;
    private javax.swing.JRadioButton jRLibra;
    private javax.swing.JRadioButton jRPeixes;
    private javax.swing.JRadioButton jRSagitario;
    private javax.swing.JRadioButton jRTouro;
    private javax.swing.JRadioButton jRVirgem;
    // End of variables declaration//GEN-END:variables
}
